zfoo-project/zfoo

- net/src/main/java/com/zfoo/net/packet/model/PacketAttachmentType.java
> fix[net]: 修改附加包bug

- monitor/src/main/java/com/zfoo/monitor/model/SystemInfoVo.java
- monitor/src/main/java/com/zfoo/monitor/util/OSUtils.java
- orm/src/main/java/com/zfoo/orm/manager/OrmManager.java
1.增加操作系统信息获取的工具类
2.增加mongodb,TTL 类型  List<Data>和Data[] 的判断
> 增加操作系统信息获取的工具类,并增加mongodb,TTL 类型  List<Data>和Data[] 的判断

- net/src/main/java/com/zfoo/net/packet/common/Error.java
- net/src/main/java/com/zfoo/net/packet/common/Message.java
class Error 添加@ProtobufClass 注解
> 添加@ProtobufClass 注解 @ignore 忽略PROTOCOL_ID

- boot/src/test/java/com/zfoo/boot/MainTest.java
- event/src/main/java/com/zfoo/event/manager/EventBus.java
- event/src/main/java/com/zfoo/event/model/anno/AsyncExecute.java
- event/src/main/java/com/zfoo/event/schema/EventRegisterProcessor.java
- event/src/test/java/com/zfoo/event/ApplicationTest.java
- event/src/test/java/com/zfoo/event/MyController1.java
- event/src/test/java/com/zfoo/event/MyController2.java
考虑这个功能：对于同个事件，如果一部分观察者想同步执行，另一部分想异步执行。
> feat[event] 将同异步处理事件的控制 由事件发布者下放到观察者

- protocol/src/main/java/com/zfoo/protocol/util/StringUtils.java
- storage/src/main/java/com/zfoo/storage/manager/StorageManager.java
- storage/src/main/java/com/zfoo/storage/model/config/StorageConfig.java
- storage/src/main/java/com/zfoo/storage/model/vo/ResourceDef.java
- storage/src/main/java/com/zfoo/storage/schema/StorageDefinitionParser.java
- storage/src/test/java/com/zfoo/storage/export/ExportBinaryTest.java
- storage/src/test/resources/application.xml
scan标签中package属性以及resource标签location属性均可以同时指定多个路径，分隔符用","  ";"或者空格
> feat[storage]:配置文件可以同时指定多个扫描路径和扫描包

- net/src/main/java/com/zfoo/net/core/AbstractClient.java
- net/src/main/java/com/zfoo/net/core/AbstractServer.java
- net/src/main/java/com/zfoo/net/core/event/ClientSessionActiveEvent.java
- net/src/main/java/com/zfoo/net/core/event/ServerSessionActiveEvent.java
- net/src/main/java/com/zfoo/net/core/gateway/GatewayServer.java
- net/src/main/java/com/zfoo/net/core/gateway/WebsocketGatewayServer.java
- net/src/main/java/com/zfoo/net/core/gateway/WebsocketSslGatewayServer.java
- net/src/main/java/com/zfoo/net/core/http/HttpServer.java
- net/src/main/java/com/zfoo/net/core/jprotobuf/JProtobufGatewayServer.java
- net/src/main/java/com/zfoo/net/core/jprotobuf/JProtobufTcpClient.java
- net/src/main/java/com/zfoo/net/core/jprotobuf/JProtobufTcpServer.java
- net/src/main/java/com/zfoo/net/core/json/JsonWebsocketClient.java
- net/src/main/java/com/zfoo/net/core/json/JsonWebsocketServer.java
- net/src/main/java/com/zfoo/net/core/tcp/TcpClient.java
- net/src/main/java/com/zfoo/net/core/tcp/TcpServer.java
- net/src/main/java/com/zfoo/net/core/udp/UdpClient.java
- net/src/main/java/com/zfoo/net/core/udp/UdpServer.java
- net/src/main/java/com/zfoo/net/core/websocket/WebsocketClient.java
- net/src/main/java/com/zfoo/net/core/websocket/WebsocketServer.java
- net/src/main/java/com/zfoo/net/handler/BaseRouteHandler.java
- net/src/main/java/com/zfoo/net/handler/ClientRouteHandler.java
- net/src/main/java/com/zfoo/net/handler/GatewayRouteHandler.java
- net/src/main/java/com/zfoo/net/handler/ServerRouteHandler.java
net.core 客户端和服务端的 session 生命周期监听支持.
> refactor[net]: adding session lifecycle consumer support

- storage/src/main/java/com/zfoo/storage/interpreter/CsvReader.java
- storage/src/main/java/com/zfoo/storage/interpreter/ExcelReader.java
- storage/src/main/java/com/zfoo/storage/interpreter/ResourceInterpreter.java
- storage/src/main/java/com/zfoo/storage/manager/StorageManager.java
- storage/src/main/java/com/zfoo/storage/model/anno/Resource.java
- storage/src/test/java/com/zfoo/storage/ApplicationTest.java
- storage/src/test/java/com/zfoo/storage/resource/StudentCsvResource.java
@Resource增加指定路径功能，主要是解决资源文件名为中文或者存在其它奇怪字符的情况
新增部分英文异常信息
> feat[storage] resource注解新增指定路径功能

- storage/src/main/java/com/zfoo/storage/interpreter/ResourceInterpreter.java
> ref[storage] rewrite code of @ExcelFieldName

- protocol/src/test/java/com/zfoo/protocol/field/FieldSpeedTest.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/BytesObject.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/FieldProtobufObject.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/InnerObject.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/InnerObjectObject.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/ListIntegerObject.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/MapObject.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/SetObject.java
- protocol/src/test/java/com/zfoo/protocol/field/packet/StringObject.java
- protocol/src/test/resources/fieldspeed.proto
测试了只包含特定数据类型的对象序列化和反序列化性能，几乎所有类型zfoo速度均优于kryo和protobuf，其中反序列化速度提升更大。
> test[protocol]add performance test of specific object

- protocol/src/main/java/com/zfoo/protocol/generate/GenerateProtocolNote.java
- Allow "\n" in `@Note` value
- Refactor generate note for class and field into one method
> [Protocol] (Add) support multiline notes

- protocol/src/main/java/com/zfoo/protocol/util/AssertionUtils.java
> fix:the le0 method parameter is incorrect

- protocol/src/main/java/com/zfoo/protocol/registration/EnhanceUtils.java
- protocol/src/main/java/com/zfoo/protocol/registration/ProtocolAnalysis.java
- protocol/src/main/java/com/zfoo/protocol/registration/ProtocolRegistration.java
- protocol/src/main/java/com/zfoo/protocol/util/ClassUtils.java
- protocol/src/main/java/com/zfoo/protocol/util/ReflectionUtils.java
- storage/src/test/java/com/zfoo/storage/export/ExportBinaryTesting.java
> fix[storage]:修复storage加入record生成协议报错

- net/src/main/java/com/zfoo/net/util/FastTreeMapIntLong.java
- protocol/src/main/java/com/zfoo/protocol/collection/CollectionUtils.java
- protocol/src/main/java/com/zfoo/protocol/util/MathSafeUtil.java
1.修复 hashCode < 0 路由问题;
2.优化解码HashMap 初始化过大
> fix indexOfNearestCeilingKey hashCode <0 and  comfortableCapacity size optimize

- protocol/src/main/java/com/zfoo/protocol/ProtocolManager.java
- protocol/src/main/java/com/zfoo/protocol/registration/ProtocolAnalysis.java
- protocol/src/test/java/com/zfoo/protocol/BenchmarkTesting.java
- protocol/src/test/java/com/zfoo/protocol/compatible/CompatibleTesting.java
- protocol/src/test/java/com/zfoo/protocol/field/FieldSpeedTesting.java
- protocol/src/test/java/com/zfoo/protocol/generate/GenerateTesting.java
- storage/src/test/java/com/zfoo/storage/export/ExportBinaryTesting.java
> perf[protocol ]:Protocol auto List by order

- protocol/src/main/java/com/zfoo/protocol/serializer/typescript/GenerateTsUtils.java
Reverts zfoo-project/zfoo#81
I test "buffer.compatibleRead(beforeReadIndex, length)" works  ok
> Revert "fix[protocol] typescript compatible"

- net/pom.xml
- protocol/pom.xml
- storage/pom.xml
- storage/src/main/java/com/zfoo/storage/interpreter/ExcelReader.java
> perf[protocol]: maven jprotobuf scope test

- hotswap/src/main/java/com/zfoo/hotswap/util/HotSwapUtils.java
> chore[hotswap]: update comment

- README.md
Have done some work to correct the typo made in README.md.
Please review it and merge
> Fix Readme.md Typos

- net/src/main/java/com/zfoo/net/consumer/registry/IRegistry.java
- net/src/main/java/com/zfoo/net/consumer/registry/ZookeeperRegistry.java
> feat[net]: get zookeeper path

- orm/src/main/java/com/zfoo/orm/config/HostConfig.java
- orm/src/main/java/com/zfoo/orm/manager/OrmManager.java
- orm/src/main/resources/orm-1.0.xsd
> feat[orm]: mongo authentication database can be configured

- orm/src/main/java/com/zfoo/orm/manager/OrmManager.java
> feat[orm]:the @Id annotation supports the ObjectId type

- net/src/main/java/com/zfoo/net/router/Router.java
1、修改Router中的receiverMap和serverReceiverAttachmentThreadLocal
2、添加异常处理方法，方便开发者继承重写
> feat[net]:modify the access modifier

- orm/src/main/java/com/zfoo/orm/cache/EntityCache.java
- orm/src/main/java/com/zfoo/orm/cache/IEntityCache.java
- orm/src/main/java/com/zfoo/orm/model/IEntity.java
- orm/src/test/java/com/zfoo/orm/cache/EmailManager.java
- orm/src/test/java/com/zfoo/orm/cache/EntityCachesTest.java
- orm/src/test/java/com/zfoo/orm/entity/UserEntity.java
- orm/src/test/java/com/zfoo/orm/entity/bag/MapEntity.java
1、EntityCache增加加载不存在则入库方法
2、测试用例
> feat[orm]: add loadAndInit method

- orm/src/main/java/com/zfoo/orm/manager/OrmManager.java
- storage/src/main/java/com/zfoo/storage/manager/StorageManager.java
> 修复被CGLIB代理时 直接赋值无效

- net/src/main/java/com/zfoo/net/config/ConfigManager.java
- net/src/main/java/com/zfoo/net/config/model/RegistryConfig.java
> feat[net]: supports the configuration of registry driver classes

- net/src/main/java/com/zfoo/net/config/ConfigManager.java
> fix[net]: fixed bug in client initialization registry

- event/src/main/java/com/zfoo/event/manager/EventBus.java
- event/src/main/java/com/zfoo/event/model/IEvent.java
IEvent接口添加异常处理方法，支持为特定事件重写exceptionHandle
> feat[event]: support exception handle for event

- net/src/main/java/com/zfoo/net/config/model/RegistryConfig.java
- net/src/main/java/com/zfoo/net/schema/NetDefinitionParser.java
- net/src/main/resources/net-1.0.xsd
> feat[net]: support xml configuration

- event/src/main/java/com/zfoo/event/manager/EventBus.java
EventBus支持异常处理的重新实现
> 有些自定义的异常不希望输出error日志，所以这里将日志输出的逻辑移到了exceptionFunction，方便开发者自己实现异常处理
> perf[event]: support the reimplementation of exception handling

- orm/src/main/java/com/zfoo/orm/codec/MapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/MapCodecProvider.java
- orm/src/main/java/com/zfoo/orm/manager/OrmManager.java
- orm/src/test/java/com/zfoo/orm/accessor/MapTest.java
- orm/src/test/java/com/zfoo/orm/entity/bag/MapEntity.java
Fix Maps MUST have string keys
处理实体类中map只能使用string作为主键
> feat[orm]: Fix Maps MUST have string keys

- orm/src/main/java/com/zfoo/orm/codec/BaseTypeKeyMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/BooleanMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/ByteMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/CharacterMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/DoubleMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/FloatMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/IntMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/LongMapCodec.java
- orm/src/main/java/com/zfoo/orm/codec/basetype/ShortMapCodec.java
> chore[orm]: simplify the code

- orm/src/main/java/com/zfoo/orm/cache/EntityCache.java
- orm/src/main/java/com/zfoo/orm/cache/IEntityCache.java
> feat[orm]: add an interface to persist the specified cache

- orm/src/main/java/com/zfoo/orm/cache/EntityCache.java
> feat[orm]:output stack information when concurrent writeh

- orm/src/main/java/com/zfoo/orm/cache/EntityCache.java
- orm/src/main/java/com/zfoo/orm/cache/IEntityCache.java
> feat[cache]: get the data in the cache

- protocol/src/main/java/com/zfoo/protocol/registration/ProtocolAnalysis.java
调整部分方法的访问修饰符
PS：兼容protobuf和zfoo时需要用这几个方法
> perf[net]: adjust access modifier

- orm/src/main/java/com/zfoo/orm/manager/OrmManager.java
> fix：orm对象嵌套当前对象,检查会循环递归堆栈溢出

- protocol/src/main/java/com/zfoo/protocol/ProtocolManager.java
- protocol/src/main/java/com/zfoo/protocol/exception/DecodeException.java
1.有些项目，不能因为一个协议异常把链接关了。
2.开发人员也需要知道，那个协议异常
> feat[protocol]: 上层需要知道是那个消息解析异常

- scheduler/src/main/java/com/zfoo/scheduler/util/LazyCache.java
> Lazy cache

- scheduler/src/main/java/com/zfoo/scheduler/util/LazyCache.java
ReentrantLock 替代 ReentrantReadWriteLock
> LazyCache - 锁机制调整
